name: open_director
description: Open Director. Video editor.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.2+5

# dart version
# https://github.com/dart-lang/sdk/blob/master/CHANGELOG.md
# 2.5.0 - 2019-09-10
# 2.4.1 - 2019-08-07
# 2.4.0 - 2019-06-27
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.2.0+3
  path: 1.8.2
  rxdart: 0.22.2
  get_it: 1.0.3+2
  file_picker: 1.3.8
  path_provider: ^2.0.11
  flutter_ffmpeg: 0.2.7
  flutter_screenutil: ^5.6.0  
  video_player:
    path: ./local_plugins/video_player
  permission_handler: ^10.2.0
  intl: 0.17.0
  open_file: ^3.2.1
  logger: 0.7.0+2
  logger_flutter: 0.7.1
  flutter_colorpicker: ^1.0.3
  dotted_border: ^2.0.0+3
  text_editor: ^0.7.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: ^6.0.4
  share_plus: ^4.5.3
  flutter_staggered_grid_view: ^0.6.2
  transparent_image: ^2.0.0
  flutter_downloader: ^1.10.0
  dio: ^4.0.6
  http: ^0.13.5
  uuid: ^3.0.7
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:  # flutter pub run flutter_launcher_icons:main
  flutter_native_splash:  # flutter pub pub run flutter_native_splash:create

flutter_icons:
  image_path_android: "assets/icon-710x599.png"
  image_path_ios: "assets/icon-710x599.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/background.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

flutter_native_splash:
  image: assets/splash.png
  color: "222222"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - packages/open_director/assets/blank-1h.mp4
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#fromstom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: OpenSans
    fonts:
    - asset: fonts/Open_Sans/OpenSans-Bold.ttf
      weight: 700
    - asset: fonts/Open_Sans/OpenSans-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Open_Sans/OpenSans-ExtraBold.ttf
      weight: 800
    - asset: fonts/Open_Sans/OpenSans-ExtraBoldItalic.ttf
      weight: 800
      style: italic
    - asset: fonts/Open_Sans/OpenSans-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Open_Sans/OpenSans-Light.ttf
      weight: 300
    - asset: fonts/Open_Sans/OpenSans-LightItalic.ttf
      weight: 300
      style: italic
    - asset: fonts/Open_Sans/OpenSans-Regular.ttf
      weight: 400
    - asset: fonts/Open_Sans/OpenSans-SemiBold.ttf
      weight: 600
    - asset: fonts/Open_Sans/OpenSans-SemiBoldItalic.ttf
      weight: 600
      style: italic
  - family: Pacifico
    fonts:
    - asset: fonts/Pacifico/Pacifico-Regular.ttf
      weight: 400
  - family: Roboto
    fonts:
    - asset: fonts/Roboto/Roboto-Black.ttf
      weight: 900
    - asset: fonts/Roboto/Roboto-BlackItalic.ttf
      weight: 900
      style: italic
    - asset: fonts/Roboto/Roboto-Bold.ttf
      weight: 700
    - asset: fonts/Roboto/Roboto-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: fonts/Roboto/Roboto-Italic.ttf
      weight: 400
      style: italic
    - asset: fonts/Roboto/Roboto-Light.ttf
      weight: 300
    - asset: fonts/Roboto/Roboto-LightItalic.ttf
      weight: 300
      style: italic
    - asset: fonts/Roboto/Roboto-Medium.ttf
      weight: 500
    - asset: fonts/Roboto/Roboto-MediumItalic.ttf
      weight: 500
      style: italic
    - asset: fonts/Roboto/Roboto-Regular.ttf
      weight: 400
    - asset: fonts/Roboto/Roboto-RegularItalic.ttf
      weight: 400
      style: italic
    - asset: fonts/Roboto/Roboto-Thin.ttf
      weight: 100
    - asset: fonts/Roboto/Roboto-ThinItalic.ttf
      weight: 100
      style: italic
  - family: Noto Naskh Arabic
    fonts:
    - asset: fonts/Noto_Naskh_Arabic/NotoNaskhArabic-VariableFont_wght.ttf 
      weight: 900
  - family: Noto Sans Arabic
    fonts:
    - asset: fonts/Noto_Sans_Arabic/NotoSansArabic-VariableFont_wdth.ttf 
      weight: 900


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/cues
